// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	task "github.com/uniqelus/todo-manager/internal/domain/server/task"
)

// TaskCreator is an autogenerated mock type for the TaskCreator type
type TaskCreator struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, opts
func (_m *TaskCreator) CreateTask(ctx context.Context, opts *task.CreateTaskOptions) (*task.Task, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.CreateTaskOptions) (*task.Task, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.CreateTaskOptions) *task.Task); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.CreateTaskOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskCreator creates a new instance of TaskCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskCreator {
	mock := &TaskCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
